---
  - name: Configure and Install ELK with Docker
    hosts: elk
    become: true
    tasks:

    - name: set maximum map count
      sysctl: name=vm.max_map_count value=262144 state=present
    
    - name: Increase virtual memory on restart
      shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf 

    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install Python Docker Module
      pip:
        name: docker
        state: present

    - name: download docker web container
      docker_container:
                     name: elk
                     image: sebp/elk:761
                     state: started
                     restart_policy: always
                     published_ports:
                                   -  5601:5601
                                   -  9200:9200
                                   -  5044:5044

    - name: Enable docker service
      systemd:
            name: docker
            enabled: yes
